#!/bin/bash
# PostToolUse hook: Auto-push Convex changes after file modifications in convex/
# Triggers on Write/Edit/MultiEdit to files in the convex/ directory
# Runs `bunx convex dev --once` to do a single push if no watcher is already running

set -euo pipefail

# Read JSON input from stdin
INPUT=$(cat)

# Extract tool name and file path
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // ""')
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')

# Only trigger on file-modifying tools
case "$TOOL_NAME" in
  Write|Edit|MultiEdit) ;;
  *) exit 0 ;;
esac

# Check if file is in the convex/ directory
case "$FILE_PATH" in
  */convex/*|convex/*) ;;
  *) exit 0 ;;
esac

# Skip generated files (they get regenerated by convex dev anyway)
case "$FILE_PATH" in
  */convex/_generated/*|convex/_generated/*) exit 0 ;;
esac

# Check if convex dev is already running (it auto-watches for changes)
if pgrep -f "convex dev" > /dev/null 2>&1; then
  echo "Convex file modified: $(basename "$FILE_PATH"). Convex dev watcher is running and will auto-sync."
  exit 0
fi

# Get project root (two levels up from this script)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# Run a one-shot convex push in the background
echo "Convex file modified: $(basename "$FILE_PATH"). Running one-shot convex push..."
cd "$PROJECT_ROOT" && bunx convex dev --once --typecheck=disable > /dev/null 2>&1 &

exit 0
