// Pure rendering functions — NO "use node", NO Convex imports
// Converts platform data into Confluence Storage Format HTML

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function createContentHash(content: string): string {
  // Simple hash based on content length and sample chars
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    hash = ((hash << 5) - hash + content.charCodeAt(i)) | 0;
  }
  return `${Math.abs(hash).toString(36)}:${content.length}`;
}

function formatDate(timestamp?: number): string {
  if (!timestamp) return "N/A";
  return new Date(timestamp).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function statusBadge(status: string): string {
  const colorMap: Record<string, string> = {
    on_track: "Green",
    at_risk: "Yellow",
    blocked: "Red",
    active: "Green",
    paused: "Yellow",
    complete: "Blue",
    archived: "Grey",
    draft: "Grey",
    approved: "Blue",
    in_progress: "Yellow",
    deferred: "Grey",
  };
  const color = colorMap[status] ?? "Grey";
  const label = status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return `<ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">${color}</ac:parameter><ac:parameter ac:name="title">${escapeHtml(label)}</ac:parameter></ac:structured-macro>`;
}

function priorityLabel(priority: string): string {
  const labels: Record<string, string> = {
    must_have: "Must Have",
    should_have: "Should Have",
    nice_to_have: "Nice to Have",
    deferred: "Deferred",
  };
  return labels[priority] ?? priority;
}

function fitGapLabel(fitGap: string): string {
  const labels: Record<string, string> = {
    native: "Native",
    config: "Config",
    custom_dev: "Custom Dev",
    third_party: "Third Party",
    not_feasible: "Not Feasible",
  };
  return labels[fitGap] ?? fitGap;
}

function effortLabel(effort?: string): string {
  if (!effort) return "TBD";
  const labels: Record<string, string> = {
    low: "Low",
    medium: "Medium",
    high: "High",
    very_high: "Very High",
  };
  return labels[effort] ?? effort;
}

export function renderProgramOverview(
  program: {
    name: string;
    clientName: string;
    sourcePlatform: string;
    targetPlatform: string;
    phase: string;
    status: string;
    startDate?: number;
    targetEndDate?: number;
    description?: string;
  },
  workstreams: Array<{
    shortCode: string;
    name: string;
    status: string;
    description?: string;
  }>,
): { html: string; contentHash: string } {
  const platformLabel = (p: string) =>
    p.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  let html = `<h1>${escapeHtml(program.name)}</h1>`;

  // Info panel
  html += `<ac:structured-macro ac:name="info"><ac:rich-text-body>`;
  html += `<p><strong>Client:</strong> ${escapeHtml(program.clientName)}</p>`;
  html += `<p><strong>Migration:</strong> ${escapeHtml(platformLabel(program.sourcePlatform))} → ${escapeHtml(platformLabel(program.targetPlatform))}</p>`;
  html += `<p><strong>Phase:</strong> ${statusBadge(program.phase)} <strong>Status:</strong> ${statusBadge(program.status)}</p>`;
  html += `<p><strong>Start:</strong> ${formatDate(program.startDate)} <strong>Target End:</strong> ${formatDate(program.targetEndDate)}</p>`;
  html += `</ac:rich-text-body></ac:structured-macro>`;

  if (program.description) {
    html += `<p>${escapeHtml(program.description)}</p>`;
  }

  // Workstreams table
  html += `<h2>Workstreams</h2>`;
  if (workstreams.length === 0) {
    html += `<p><em>No workstreams configured yet.</em></p>`;
  } else {
    html += `<table><thead><tr><th>Code</th><th>Name</th><th>Status</th><th>Description</th></tr></thead><tbody>`;
    for (const ws of workstreams) {
      html += `<tr>`;
      html += `<td><strong>${escapeHtml(ws.shortCode)}</strong></td>`;
      html += `<td>${escapeHtml(ws.name)}</td>`;
      html += `<td>${statusBadge(ws.status)}</td>`;
      html += `<td>${ws.description ? escapeHtml(ws.description) : ""}</td>`;
      html += `</tr>`;
    }
    html += `</tbody></table>`;
  }

  // Generated timestamp
  html += `<hr/><p><em>Generated by Migration Conductor on ${formatDate(Date.now())}</em></p>`;

  const contentHash = createContentHash(html);
  return { html, contentHash };
}

export function renderGapAnalysis(
  requirements: Array<{
    refId: string;
    title: string;
    priority: string;
    fitGap: string;
    effortEstimate?: string;
    status: string;
    workstreamId?: string;
    description?: string;
  }>,
  workstreams: Array<{
    _id: string;
    shortCode: string;
    name: string;
  }>,
): { html: string; contentHash: string } {
  const wsMap = new Map(workstreams.map((ws) => [ws._id, ws]));

  // Summary stats
  const total = requirements.length;
  const byFitGap: Record<string, number> = {};
  const byPriority: Record<string, number> = {};
  for (const req of requirements) {
    byFitGap[req.fitGap] = (byFitGap[req.fitGap] ?? 0) + 1;
    byPriority[req.priority] = (byPriority[req.priority] ?? 0) + 1;
  }

  let html = `<h1>Gap Analysis Report</h1>`;

  // Summary panel
  html += `<ac:structured-macro ac:name="info"><ac:rich-text-body>`;
  html += `<p><strong>Total Requirements:</strong> ${total}</p>`;
  html += `<p><strong>By Priority:</strong> `;
  html += Object.entries(byPriority)
    .map(([k, v]) => `${priorityLabel(k)}: ${v}`)
    .join(" | ");
  html += `</p>`;
  html += `<p><strong>By Fit/Gap:</strong> `;
  html += Object.entries(byFitGap)
    .map(([k, v]) => `${fitGapLabel(k)}: ${v}`)
    .join(" | ");
  html += `</p>`;
  html += `</ac:rich-text-body></ac:structured-macro>`;

  // Group by workstream
  const grouped = new Map<string, typeof requirements>();
  const unassigned: typeof requirements = [];

  for (const req of requirements) {
    if (req.workstreamId) {
      const group = grouped.get(req.workstreamId) ?? [];
      group.push(req);
      grouped.set(req.workstreamId, group);
    } else {
      unassigned.push(req);
    }
  }

  function renderReqTable(reqs: typeof requirements): string {
    let t = `<table><thead><tr><th>Ref ID</th><th>Title</th><th>Priority</th><th>Fit/Gap</th><th>Effort</th><th>Status</th></tr></thead><tbody>`;
    for (const req of reqs) {
      t += `<tr>`;
      t += `<td><strong>${escapeHtml(req.refId)}</strong></td>`;
      t += `<td>${escapeHtml(req.title)}</td>`;
      t += `<td>${escapeHtml(priorityLabel(req.priority))}</td>`;
      t += `<td>${escapeHtml(fitGapLabel(req.fitGap))}</td>`;
      t += `<td>${escapeHtml(effortLabel(req.effortEstimate))}</td>`;
      t += `<td>${statusBadge(req.status)}</td>`;
      t += `</tr>`;
    }
    t += `</tbody></table>`;
    return t;
  }

  // Render each workstream section
  for (const [wsId, reqs] of grouped) {
    const ws = wsMap.get(wsId);
    const label = ws ? `${ws.shortCode} - ${ws.name}` : "Unknown Workstream";
    html += `<h2>${escapeHtml(label)}</h2>`;
    html += renderReqTable(reqs);
  }

  if (unassigned.length > 0) {
    html += `<h2>Unassigned</h2>`;
    html += renderReqTable(unassigned);
  }

  html += `<hr/><p><em>Generated by Migration Conductor on ${formatDate(Date.now())}</em></p>`;

  const contentHash = createContentHash(html);
  return { html, contentHash };
}
